# Generated by Django 4.0.2 on 2022-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctaccess',
            name='time_out_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
