# Generated by Django 4.0.2 on 2022-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_correctaccess_time_out_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctaccess',
            name='time_in_days',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correctaccess',
            name='time_out_days',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
