# Generated by Django 4.0.2 on 2022-02-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_correctaccess_time_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_id', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='approval',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeapproval', to='hr.employee'),
        ),
    ]
